from __future__ import division, absolute_import, print_function

import pytest
import sys

import numpy as np
import psi4

sys.path.insert(1, '../')

import driver as resp


def test_resp_unconstrained_a():
    ''' One-stage fitting of charges.

        - ESP is compute using Psi4
        - resp_a = 0.001

        Reference charges were generated by R.E.D.-III.5 and GAMESS.
    '''

    reference_charges = np.array([-0.294974,  0.107114,  0.107114,  0.084795,
                                   0.803999, -0.661279,  0.453270, -0.600039])

    charges = resp.resp('resp_unconstrained_a.ini')

    print('Unrestrained Electrostatic Potential Charges')
    print(f'{charges[0]}\n')

    print('Restrained Electrostatic Potential (RESP) Charges')
    print(f'{charges[1]}\n')

    print('Reference RESP Charges (via RED-III 5)')
    print(f'{reference_charges}\n')

    print('Difference')
    print(f'{charges[1]-reference_charges}\n')

    assert np.allclose(charges[1], reference_charges, atol=5e-4)


def test_resp_unconstrained_b():
    ''' One-stage fitting of charges.

        - ESP is read in (i.e., output from previous test)
        - resp_a = 0.001

        Reference charges were generated by R.E.D.-III.5 and GAMESS.
    '''

    reference_charges = np.array([-0.294974,  0.107114,  0.107114,  0.084795,
                                   0.803999, -0.661279,  0.453270, -0.600039])

    charges = resp.resp('resp_unconstrained_b.ini')

    print('Unrestrained Electrostatic Potential Charges')
    print(f'{charges[0]}\n')

    print('Restrained Electrostatic Potential (RESP) Charges')
    print(f'{charges[1]}\n')

    print('Reference RESP Charges (via RED-III 5)')
    print(f'{reference_charges}\n')

    print('Difference')
    print(f'{charges[1]-reference_charges}\n')

    assert np.allclose(charges[1], reference_charges, atol=5e-4)


def test_resp_constrained_a():
    ''' Two-stage fitting of charges.

        - ESP is compute using Psi4
        - resp_a = 0.001
        - last four atoms constrained to certain values
        - methyl hydrogens force to be equivalent
    '''

    reference_charges = np.array([-0.290893,  0.098314,  0.098314,  0.098314,
                                   0.803999, -0.661279,  0.453270, -0.600039])

    charges = resp.resp('resp_constrained_a.ini')

    print('Unrestrained Electrostatic Potential Charges')
    print(f'{charges[0]}\n')

    print('Restrained Electrostatic Potential (RESP) Charges')
    print(f'{charges[1]}\n')

    print('Reference RESP Charges (via RED-III 5)')
    print(f'{reference_charges}\n')

    print('Difference')
    print(f'{charges[1]-reference_charges}\n')

    assert np.allclose(charges[1], reference_charges, atol=5e-4)


def test_resp_two_conformers_a():
    ''' One-stage fitting of charges using two conformations.

        - ESP is compute using Psi4
        - resp_a = 0.0005
    '''

    reference_charges = np.array([-0.149134, 0.274292, -0.630868,  0.377965, -0.011016,
                                  -0.009444, 0.058576,  0.044797,  0.044831])

    charges = resp.resp('resp_two_confs_a.ini')

    print('Unrestrained Electrostatic Potential Charges')
    print(f'{charges[0]}\n')

    print('Restrained Electrostatic Potential (RESP) Charges')
    print(f'{charges[1]}\n')

    print('Reference RESP Charges (via RED-III 5)')
    print(f'{reference_charges}\n')

    print('Difference')
    print(f'{charges[1]-reference_charges}\n')

    assert np.allclose(charges[1], reference_charges, atol=1e-5)


def test_resp_two_conformers_b():
    ''' Note: the comparison tolerance had to be slightly adjusted here
            to 1.5e-5 for the assert to be passed.
    '''
    reference_charges = np.array([-0.079853, 0.253918, -0.630868, 0.377965, -0.007711,
                                  -0.007711, 0.031420,  0.031420, 0.031420])

    charges = resp.resp('resp_two_confs_b.ini')

    print('Unrestrained Electrostatic Potential Charges')
    print(f'{charges[0]}\n')

    print('Restrained Electrostatic Potential (RESP) Charges')
    print(f'{charges[1]}\n')

    print('Reference RESP Charges (via RED-III 5)')
    print(f'{reference_charges}\n')

    print('Difference')
    print(f'{charges[1]-reference_charges}\n')

    assert np.allclose(charges[1], reference_charges, atol=1.5e-5)