from __future__ import division, absolute_import, print_function

import os
import pytest
import sys

import numpy as np
import psi4

# Check if we are in the 'tests' directory
if not os.path.basename(os.getcwd()) == 'tests':
    pytest.exit("ERROR: This test suite must be run from within the /tests directory "
                "due to relative path dependencies for .ini and .xyz files.")

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), '..', 'src')))
#sys.path.insert(1, '../src/')

import driver as resp


def test_resp_unconstrained_a():
    ''' One-stage fitting of charges.

        - Molecule: acetic_acid.xyz
        - ESP is compute using Psi4
        - resp_a = 0.0005
        - resp_b = 0.1

        Reference charges were generated by R.E.D.-III.5 and GAMESS.
    '''

    reference_charges = np.array([-0.294974,  0.107114,  0.107114,  0.084795,
                                   0.803999, -0.661279,  0.453270, -0.600039])

    charges = resp.resp('resp_unconstrained_a.ini')

    print('Unrestrained Electrostatic Potential Charges')
    print(f'{charges[0]}\n')

    print('Restrained Electrostatic Potential (RESP) Charges')
    print(f'{charges[1]}\n')

    print('Reference RESP Charges (via RED-III 5)')
    print(f'{reference_charges}\n')

    print('Difference')
    print(f'{charges[1]-reference_charges}\n')

    assert np.allclose(charges[1], reference_charges, atol=5.0e-4)


def test_resp_unconstrained_b():
    ''' One-stage fitting of charges.

        - Molecule: acetic_acid.xyz
        - ESP is read in (i.e., output from previous test)
        - resp_a = 0.0005
        - resp_b = 0.1

        Reference charges were generated by R.E.D.-III.5 and GAMESS.
    '''

    reference_charges = np.array([-0.294974,  0.107114,  0.107114,  0.084795,
                                   0.803999, -0.661279,  0.453270, -0.600039])

    charges = resp.resp('resp_unconstrained_b.ini')

    print('Unrestrained Electrostatic Potential Charges')
    print(f'{charges[0]}\n')

    print('Restrained Electrostatic Potential (RESP) Charges')
    print(f'{charges[1]}\n')

    print('Reference RESP Charges (via RED-III 5)')
    print(f'{reference_charges}\n')

    print('Difference')
    print(f'{charges[1]-reference_charges}\n')

    assert np.allclose(charges[1], reference_charges, atol=5.0e-4)


def test_resp_constrained_a():
    ''' Two-stage fitting of charges.
            constraint_charge : 5 =  0.8043282118269929,
                                6 = -0.6614656885808026,
                                7 =  0.45334412484467956,
                                8 = -0.6002604772446537

        - Molecule: acetic_acid.xyz
        - ESP is compute using Psi4
        - resp_a = 0.001
        - resp_b = 0.1
        - last four atoms constrained to certain values
        - methyl hydrogens force to be equivalent
    '''

    reference_charges = np.array([-0.290893,  0.098314,  0.098314,  0.098314,
                                   0.803999, -0.661279,  0.453270, -0.600039])

    charges = resp.resp('resp_constrained_a.ini')

    print('Unrestrained Electrostatic Potential Charges')
    print(f'{charges[0]}\n')

    print('Restrained Electrostatic Potential (RESP) Charges')
    print(f'{charges[1]}\n')

    print('Reference RESP Charges (via RED-III 5)')
    print(f'{reference_charges}\n')

    print('Difference')
    print(f'{charges[1]-reference_charges}\n')

    assert np.allclose(charges[1], reference_charges, atol=5.0e-4)


def test_resp_two_conformers_a():
    ''' One-stage fitting of charges using two conformations.

        - Molecule: ethanol_1.xyz, ethanol_2.xyz
        - ESP is compute using Psi4
        - resp_a = 0.0005
        - resp_b = 0.1
    '''

    reference_charges = np.array([-0.149134, 0.274292, -0.630868,  0.377965, -0.011016,
                                  -0.009444, 0.058576,  0.044797,  0.044831])

    charges = resp.resp('resp_two_confs_a.ini')

    print('Unrestrained Electrostatic Potential Charges')
    print(f'{charges[0]}\n')

    print('Restrained Electrostatic Potential (RESP) Charges')
    print(f'{charges[1]}\n')

    print('Reference RESP Charges (via RED-III 5)')
    print(f'{reference_charges}\n')

    print('Difference')
    print(f'{charges[1]-reference_charges}\n')

    assert np.allclose(charges[1], reference_charges, atol=1.0e-5)


def test_resp_two_conformers_b():
    '''  Two-stage fitting of charges.
            constraint_charge : 3 = -0.63087078,
                                4 = 0.377965

        - Molecule: ethanol_1.xyz, ethanol_2.xyz
        - ESP is read in (i.e., output from previous test)
        - resp_a = 0.001
        - resp_b = 0.1

    '''
    reference_charges = np.array([-0.079853, 0.253918, -0.630868, 0.377965, -0.007711,
                                  -0.007711, 0.031420,  0.031420, 0.031420])

    charges = resp.resp('resp_two_confs_b.ini')

    print('Unrestrained Electrostatic Potential Charges')
    print(f'{charges[0]}\n')

    print('Restrained Electrostatic Potential (RESP) Charges')
    print(f'{charges[1]}\n')

    print('Reference RESP Charges (via RED-III 5)')
    print(f'{reference_charges}\n')

    print('Difference')
    print(f'{charges[1]-reference_charges}\n')

    assert np.allclose(charges[1], reference_charges, atol=1.5e-5)


def test_bromoethene():
    '''  Single-stage fitting of charges.
    '''
    reference_charges = np.array([-0.22793428, 0.14970713, 0.17055694, -0.23219228,
                                  -0.08681686, 0.22667934])

    charges = resp.resp('bromoethene.ini')

    print('Unrestrained Electrostatic Potential Charges')
    print(f'{charges[0]}\n')

    print('Restrained Electrostatic Potential (RESP) Charges')
    print(f'{charges[1]}\n')

    print('Reference RESP Charges (via RED-III 5)')
    print(f'{reference_charges}\n')

    print('Difference')
    print(f'{charges[1]-reference_charges}\n')

    assert np.allclose(charges[1], reference_charges, atol=1.0e-5)


def test_bromoethene_x():
    '''  Single-stage fitting of charges.
    '''
    reference_charges = np.array([-0.37318215, 0.16577433, 0.21990568, -0.00848194,
                                  -0.26039446, 0.17776180, 0.07861675])

    charges = resp.resp('bromoethene_x.ini')

    print('Unrestrained Electrostatic Potential Charges')
    print(f'{charges[0]}\n')

    print('Restrained Electrostatic Potential (RESP) Charges')
    print(f'{charges[1]}\n')

    print('Reference RESP Charges (via RED-III 5)')
    print(f'{reference_charges}\n')

    print('Difference')
    print(f'{charges[1]-reference_charges}\n')

    assert np.allclose(charges[1], reference_charges, atol=1.0e-5)